import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
Deno.serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
 if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers:cors});
 const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
 const auth=req.headers.get("Authorization")||"";
 const userClient=createClient(url,anon,{global:{headers:{Authorization:auth}}});
 const {data:{user}}=await userClient.auth.getUser();
 if(!user)return new Response(JSON.stringify({error:"Sign in required"}),{status:401,headers:cors});
 const admin=createClient(url,service);
 const {count,error}=await admin.from("pythonpath_progress").select("lesson_id",{count:"exact",head:true}).eq("user_id",user.id).eq("status","completed");
 if(error)return new Response(JSON.stringify({error:error.message}),{status:500,headers:cors});
 if((count||0)<12)return new Response(JSON.stringify({error:`Complete all 12 starter lessons first. Completed: ${count||0}/12`} ),{status:400,headers:cors});
 const {data:existing}=await admin.from("pythonpath_certificates").select("*").eq("user_id",user.id).maybeSingle();
 if(existing)return new Response(JSON.stringify({certificate:existing}),{headers:cors});
 const code="PY-"+crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase();
 const {data,error:insertError}=await admin.from("pythonpath_certificates").insert({user_id:user.id,certificate_code:code,verified:true,completed_lessons:count}).select("*").single();
 if(insertError)return new Response(JSON.stringify({error:insertError.message}),{status:500,headers:cors});
 return new Response(JSON.stringify({certificate:data}),{headers:cors});
});
